version: '3.8'

services:
  db:
    image: library/postgres:12.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  db-flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db
