name: Create file

on:
  schedule: 
    - cron:  '0 9 * * *'

  workflow_dispatch:

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: create file
        run: touch test/"$(date +%Y-%m-%dT%H:%M:%S)"
      
      - name: commit & push
        run: |
          git config user.name ${{ secrets.GIT_ACCOUNT }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git branch
          git add .
          git commit -m "Create"
          git push origin main
