# This is a basic workflow to help you get started with Actions

name: Create file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule: 
    - cron:  '0 9 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create file
        run: touch test/"$(date +%Y-%m-%dT%H:%M:%S)"
      
      - name: commit & push
        run: |
          git config user.name ${{ secrets.GIT_ACCOUNT }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git add .
          git commit -m "Create"
          git push
