name: Update Database docs

on:
  push:
    branches:
      - main
    paths:
      - db/migration/**

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: run database
        run: docker-compose up -d

      - name: create file
        run: docker run -v "$PWD/docs/db:/output" --net="host" schemaspy/schemaspy:snapshot -t pgsql -host host.docker.internal:5432 -db postgres -u postgres -p password

      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Create"
          git push origin main
