name: Update Database docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - db/migration/**

jobs:
  database_docs:
    runs-on: ubuntu-latest
    env:
      DOCS_DIR: docs/db

    steps:
      - uses: actions/checkout@v3.1.0

      - name: run database
        run: docker-compose up -d

      - name: clean docs
        run: rm -rf ${{ env.DOCS_DIR }}

      - name: run schemaspy
        run: docker run -u root -v "$PWD/${{ env.DOCS_DIR }}:/output" --net="host" schemaspy/schemaspy:snapshot -t pgsql -host $(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):5432 -db postgres -u postgres -p password

      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          BRANCH=docs/db/$(date +%Y%m%d%H%M%S)
          git switch -c $BRANCH
          git add ${{ env.DOCS_DIR }}
          git commit -m "Update database docs"
          git push --set-upstream origin $BRANCH
          gh pr create --title "Update Database docs" --body ":+1:"
          gh pr review --comment -b ":+1:"
          gh pr merge --squash $BRANCH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
