name: Update Database docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - db/migration/**

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: run database
        run: docker-compose up -d

      - name: create file
        run: docker run -u root -v "$PWD/docs/db:/output" --net="host" schemaspy/schemaspy:snapshot -t pgsql -host $(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):5432 -db postgres -u postgres -p password

      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c docs/db
          git add .
          git commit -m "Create"
          gh pr create --title "Update Database docs" --body ":+1:"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
